### ISSUE TITLE
No control over ttl in StorageCollection

### ISSUE THREAD

**Issue by red-led** [ICanBoogie/Storage#3]
Hi! 
First of all thanks for this lib, it's really nice.

I encountered small problem. `StorageCollection::retrieve` calls `store` on every storage where key was not found, but you can't set any ttl for it. For Redis it means to store forever, and can be undesirable.

**Comment by red-led** [comment]
@olvlvl, I'm going to implement this. There's 2 ways:
* add `ttl` parameter to `StorageCollection::retrieve` mehod
* add `ttl` field to `StorageCollection` class

Which would you prefer?

**Comment by olvlvl** [comment]
Having `ttl` as an optional constructor parameter would be a good idea. Could you open a PR?

**Comment by olvlvl** [comment]
@red-led FYI: https://github.com/ICanBoogie/Storage/pull/8
